[metadata]
name = nvidia-manager
version = 0.1.0
description = NVIDIA Driver Manager — GUI tool for Debian/Ubuntu based distributions to manage NVIDIA drivers and CUDA toolkits.
long_description = file: README.md
author = kimocoder
license = MIT
url = https://github.com/kimocoder/nvidia-manager

[options]
packages = find:
python_requires = >=3.10
include_package_data = False
install_requires =

[options.packages.find]
exclude =
    *.__pycache__
    *.__pycache__.*

[flake8]
max-line-length = 120
exclude =
    build,
    .venv,
    venv,
    IntelTensorFlow_InferenceOptimization,
    MangoHud,
    build/lib,
    v1,


